---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: service_2:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: service-2
  type: ClusterIP
